@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.socketmods.socketnukes.capability.exploderconfig;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;