@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.socketmods.socketnukes.client.events;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;