@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.socketmods.socketnukes.actors.example;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;