@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.socketmods.socketnukes.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;