@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.socketmods.socketnukes.container.slot;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;